// Code generated by protoc-gen-go.
// source: github.com/3zheng/railgun/protodefine/tcpnet/tcp.proto
// DO NOT EDIT!

/*
Package bs_tcp is a generated protocol buffer package.

It is generated from these files:
	github.com/3zheng/railgun/protodefine/tcpnet/tcp.proto

It has these top-level messages:
	TCPTransferMsg
	TCPSessionCome
	TCPSessionClose
	TCPSessionKick
*/
package bs_tcp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bs_types "github.com/3zheng/railgun/protodefine/mytype"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMDID_Tcp int32

const (
	CMDID_Tcp_IDUnknow          CMDID_Tcp = 0
	CMDID_Tcp_IDTCPTransferMsg  CMDID_Tcp = 1
	CMDID_Tcp_IDTCPSessionCome  CMDID_Tcp = 2
	CMDID_Tcp_IDTCPSessionClose CMDID_Tcp = 3
	CMDID_Tcp_IDTCPSessionKick  CMDID_Tcp = 4
	CMDID_Tcp_IDLast            CMDID_Tcp = 100
)

var CMDID_Tcp_name = map[int32]string{
	0:   "IDUnknow",
	1:   "IDTCPTransferMsg",
	2:   "IDTCPSessionCome",
	3:   "IDTCPSessionClose",
	4:   "IDTCPSessionKick",
	100: "IDLast",
}
var CMDID_Tcp_value = map[string]int32{
	"IDUnknow":          0,
	"IDTCPTransferMsg":  1,
	"IDTCPSessionCome":  2,
	"IDTCPSessionClose": 3,
	"IDTCPSessionKick":  4,
	"IDLast":            100,
}

func (x CMDID_Tcp) String() string {
	return proto.EnumName(CMDID_Tcp_name, int32(x))
}
func (CMDID_Tcp) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TCPTransferMsg struct {
	Base       *bs_types.BaseInfo `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	DataKindId uint32             `protobuf:"varint,2,opt,name=data_kind_id,json=dataKindId" json:"data_kind_id,omitempty"`
	DataSubId  uint32             `protobuf:"varint,3,opt,name=data_sub_id,json=dataSubId" json:"data_sub_id,omitempty"`
	Data       []byte             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *TCPTransferMsg) Reset()                    { *m = TCPTransferMsg{} }
func (m *TCPTransferMsg) String() string            { return proto.CompactTextString(m) }
func (*TCPTransferMsg) ProtoMessage()               {}
func (*TCPTransferMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TCPTransferMsg) GetBase() *bs_types.BaseInfo {
	if m != nil {
		return m.Base
	}
	return nil
}

type TCPSessionCome struct {
	Base *bs_types.BaseInfo `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (m *TCPSessionCome) Reset()                    { *m = TCPSessionCome{} }
func (m *TCPSessionCome) String() string            { return proto.CompactTextString(m) }
func (*TCPSessionCome) ProtoMessage()               {}
func (*TCPSessionCome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TCPSessionCome) GetBase() *bs_types.BaseInfo {
	if m != nil {
		return m.Base
	}
	return nil
}

type TCPSessionClose struct {
	Base *bs_types.BaseInfo `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (m *TCPSessionClose) Reset()                    { *m = TCPSessionClose{} }
func (m *TCPSessionClose) String() string            { return proto.CompactTextString(m) }
func (*TCPSessionClose) ProtoMessage()               {}
func (*TCPSessionClose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TCPSessionClose) GetBase() *bs_types.BaseInfo {
	if m != nil {
		return m.Base
	}
	return nil
}

type TCPSessionKick struct {
	Base *bs_types.BaseInfo `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (m *TCPSessionKick) Reset()                    { *m = TCPSessionKick{} }
func (m *TCPSessionKick) String() string            { return proto.CompactTextString(m) }
func (*TCPSessionKick) ProtoMessage()               {}
func (*TCPSessionKick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TCPSessionKick) GetBase() *bs_types.BaseInfo {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterType((*TCPTransferMsg)(nil), "bs.tcp.TCPTransferMsg")
	proto.RegisterType((*TCPSessionCome)(nil), "bs.tcp.TCPSessionCome")
	proto.RegisterType((*TCPSessionClose)(nil), "bs.tcp.TCPSessionClose")
	proto.RegisterType((*TCPSessionKick)(nil), "bs.tcp.TCPSessionKick")
	proto.RegisterEnum("bs.tcp.CMDID_Tcp", CMDID_Tcp_name, CMDID_Tcp_value)
}

func init() {
	proto.RegisterFile("github.com/3zheng/railgun/protodefine/tcpnet/tcp.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xed, 0x56, 0x86, 0x7b, 0x9b, 0x1a, 0x83, 0xc2, 0xf0, 0x20, 0x63, 0x07, 0x11, 0x0f,
	0x2d, 0x38, 0x90, 0x79, 0x75, 0xbd, 0x94, 0x39, 0x90, 0x6d, 0x9e, 0x47, 0xd2, 0x64, 0x5d, 0xd8,
	0x96, 0x94, 0x26, 0x45, 0xe6, 0xc1, 0x3f, 0xc1, 0xbf, 0xd9, 0x24, 0x82, 0x6c, 0x9e, 0x7a, 0x69,
	0xfb, 0x7e, 0xef, 0xfb, 0xde, 0xfb, 0x9a, 0xc0, 0x53, 0x2e, 0xcc, 0xba, 0xa2, 0x51, 0xa6, 0x76,
	0xf1, 0xf0, 0x73, 0xcd, 0x65, 0x1e, 0x97, 0x44, 0x6c, 0xf3, 0x4a, 0xc6, 0x45, 0xa9, 0x8c, 0x62,
	0x7c, 0x25, 0x24, 0x8f, 0x4d, 0x56, 0x48, 0x6e, 0xdc, 0x2b, 0xf2, 0x18, 0xb7, 0xa8, 0x8e, 0x6c,
	0x75, 0x33, 0xaa, 0xe7, 0xdf, 0xed, 0xcd, 0xbe, 0xb0, 0x63, 0xec, 0x43, 0xff, 0x4e, 0x18, 0x7c,
	0x07, 0x70, 0xbe, 0x18, 0xbf, 0x2d, 0x4a, 0x22, 0xf5, 0x8a, 0x97, 0x53, 0x9d, 0xe3, 0x3b, 0x08,
	0x29, 0xd1, 0xbc, 0x17, 0xf4, 0x83, 0xfb, 0xce, 0x23, 0x8e, 0xdc, 0x0e, 0xef, 0x78, 0xb1, 0x34,
	0x95, 0x2b, 0x35, 0xf3, 0x7d, 0xdc, 0x87, 0x2e, 0x23, 0x86, 0x2c, 0x37, 0x42, 0xb2, 0xa5, 0x60,
	0xbd, 0x86, 0xd5, 0x9f, 0xcd, 0xc0, 0xb1, 0x89, 0x45, 0x29, 0xc3, 0xb7, 0xd0, 0xf1, 0x0a, 0x5d,
	0x51, 0x27, 0x68, 0x7a, 0x41, 0xdb, 0xa1, 0x79, 0x45, 0x6d, 0x1f, 0x43, 0xe8, 0x8a, 0x5e, 0x68,
	0x1b, 0xdd, 0x99, 0xff, 0x1e, 0x8c, 0x7c, 0x9e, 0x39, 0xd7, 0x5a, 0x28, 0x39, 0x56, 0x3b, 0x5e,
	0x37, 0xcf, 0xe0, 0x19, 0x2e, 0x0e, 0x9c, 0x5b, 0xa5, 0xeb, 0x5b, 0x8f, 0x96, 0x4e, 0x44, 0xb6,
	0xa9, 0xeb, 0x7c, 0xf8, 0x82, 0xf6, 0x78, 0x9a, 0xa4, 0xc9, 0x72, 0x91, 0x15, 0xb8, 0x0b, 0xa7,
	0x69, 0xf2, 0x2e, 0x37, 0x52, 0x7d, 0xa0, 0x13, 0x7c, 0x05, 0x28, 0x4d, 0x8e, 0xcf, 0x16, 0x05,
	0x7f, 0xf4, 0xe0, 0x0f, 0x51, 0x03, 0x5f, 0xc3, 0xe5, 0x11, 0x75, 0xe9, 0x51, 0xf3, 0xbf, 0xd8,
	0x25, 0x43, 0x21, 0x06, 0x68, 0xa5, 0xc9, 0x2b, 0xd1, 0x06, 0x31, 0xda, 0xf2, 0xd7, 0x38, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x88, 0xfd, 0xee, 0x7c, 0x42, 0x02, 0x00, 0x00,
}
